#!/bin/sh

# find node
NODE=$(which node)

# if it cannot find a node installation
if [[ -z $NODE ]]; then
	#NodeJS is not installed
	echo "Please install NodeJS first."
	exit 1
fi

# make sure jslint is installed
if [[ ! -d ~/.npm/jslint ]]; then
	#install jslint locally
	echo "Please install jslint (global )first."
	exit 1
fi

for file in $(git diff --name-only --cached | egrep '.js$');
do
	echo "=~=~=~=~=~=~=~= $file"
	$NODE ./test/static-analyzer/node_modules/jslint/bin/jslint.js $file
done
exit 0


 
# run JSLint before every commit, don't commit until
# JSLint is OK
for file in $(git diff --name-only | egrep '.js$');
do
	echo "--- $file"
	#$NODE ~/.npm/jslint/bin/jslint.js $file
	## If the result of the previous command is NOT zero
	#if [ $? -ne 0 ]; then
	# echo "*** ERROR *** : JSLint failed for file: $file, please fix code and recommit"
	# exit 1
	#fi
done

exit 1
 
# Everything is ok
exit 0
