#!/bin/sh

# find node
NODE=$(which node)
JSLINT=./test/static-analyzer/node_modules/jslint
BRANCH=`git branch | awk '/\*/ { print $2; }'`

# if it cannot find a node installation
if [[ -z $NODE ]]; then
	#NodeJS is not installed
	echo "Please install NodeJS first."
	exit 1
fi

# make sure jslint is installed
if [[ ! -d $JSLINT ]]; then
	#install jslint locally
	echo "Please install jslint first."
	echo "  jslint is expected to be installed in test/static-analyzer/."
	exit 1
fi
echo "\n\n\nCurrent branch: $BRANCH\n\n\n"

# Commit and push always to development
# Only commit to test, if static analysis is passed
if [[ $BRANCH -eq "development" ]]; then
	echo "Current branch is development. This will be committed."
	exit 0
fi

for file in $(git diff --name-only --cached | egrep '.js$');
do
	echo "Verifying file $file"
	$NODE $JSLINT/bin/jslint.js $file
	if [ $? -ne 0 ]; then
		echo "*** ERROR *** : JSLint failed for file: $file, please fix code and recommit"
		exit 1
	fi
done
exit 0

# Everything is ok
exit 0
